vich_uploader:
    db_driver: orm

    mappings:
        buttonplant_images:
            uri_prefix: '%app.path.buttonplant_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.buttonplant_images%'
        buttonanimal_images:
            uri_prefix: '%app.path.buttonanimal_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.buttonanimal_images%'
        finalsheet_images:
            uri_prefix: '%app.path.finalsheet_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.finalsheet_images%'
